<?php

namespace Tests\Feature;

use App\Models\Brand;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class BrandControllerTest extends TestCase
{
    private $brand;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $attr = [
            'name' => $this->faker->name,
            'description' => $this->faker->sentence
        ];

        $this->brand = Brand::create($attr);

    }

    /**
     * @test
     * @testdox Index controller
     * @group ignore
     */
    public function testIndex()
    {

        $response = $this->getJson('/api/brands');
        $response
            ->assertStatus(200)
            ->assertSeeText($this->brand->name)
            ->assertSeeText($this->brand->description);
    }

    public function testStore()
    {
        $attr = [
            'name' => $this->faker->name,
            'description' => $this->faker->sentence
        ];


        $response = $this->postJson( '/api/brands', $attr);
        $response
            ->assertStatus(201)
            ->assertSeeText($attr['name'])
            ->assertSeeText($attr['description']);

    }
    public function testStoreNameNotNull()
    {

        $response = $this->postJson( '/api/brands',[
            'name' => ''
        ]);
        $response
            ->assertStatus(422)
            ->assertJsonValidationErrors(['name']);


    }

    public function testStoreValidationNameMax()
    {

        $response = $this->postJson( '/api/brands',[
            'name' => $this->faker->sentence(258)
        ]);
        $response
            ->assertStatus(422)
            ->assertJsonValidationErrors(['name']);

    }



    public function testShow()
    {

        $response = $this->getJson('/api/brands/' . $this->brand->id );
        $response
            ->assertStatus(200)
            ->assertSeeText($this->brand->name)
            ->assertSeeText($this->brand->description);

    }

    public function testUpdate()
    {
        $name = $this->faker->name;

        $response = $this->putJson('/api/brands/'. $this->brand->id, [
            'name' => $name
        ]);

        $response
            ->assertStatus(200)
            ->assertSeeText($name);


    }

    public function testUpdateNameNotNull()
    {

        $response = $this->putJson('/api/brands/'. $this->brand->id, [
            'name' => ''
        ]);

        $response
            ->assertStatus(422)
            ->assertJsonValidationErrors(['name']);

    }

    public function testUpdateDescriptionNull()
    {

        $response = $this->putJson('/api/brands/'. $this->brand->id, [
            'name' => $this->faker->name,
            'description' => null
        ]);

        $response->assertStatus(200);
        $this->assertNull($response->json('description'));

    }

    public function testDestroy()
    {

        $response = $this->deleteJson('/api/brands/' . $this->brand->id);
        $response
            ->assertStatus(204)
            ->assertNoContent();

    }
}
