<?php

namespace Tests\Feature;

use App\Models\Brand;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class BrandModelTest extends TestCase
{
    private $brand;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $attr = [
            'name' => $this->faker->name,
            'description' => $this->faker->sentence
        ];

        $this->brand = Brand::create($attr);
    }

    /**
     * @test
     * @testdox Adding Brand
     */
    public function testNewBrand()
    {
        $this->assertDatabaseHas('brands', $this->brand->getAttributes());

    }

    /**
     * @test
     * @testdox Updating Brand
     */
    public function testUpdateBrand()
    {
        $this->brand->description = null;
        $this->brand->save();
        $this->assertNull($this->brand->description);
        $this->assertDatabaseHas('brands', $this->brand->getAttributes());
    }

    /**
     * @test
     * @testdox Showing Brand
     */
    public function testShowBrand()
    {
        self::assertDatabaseHas('brands', $this->brand->getAttributes());
    }

    /**
     * @test
     * @testdox Removing Brand
     */
    public function testDestroyBrand()
    {
        $this->brand->delete();
        $this->assertSoftDeleted('brands', $this->brand->getAttributes());
    }
}
